import { Container, Flex } from "@chakra-ui/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { fetchToken, fetchUser } from "../../utils/fetchData";
import CategoryBar from "./CategoryBar";
import Navbar from "./Navbar";

const Layout = ({ children }) => {
	const router = useRouter();
	const [user, setUser] = useState(null);

	useEffect(() => {
		const token = fetchToken();
		if (token) {
			const [userInfo] = fetchUser();
			setUser(userInfo);
		}
	}, []);
	return (
		<>
			<Head>
				<title>Video Blog</title>
				<meta name="description" content="Generated by Khoa" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar user={user} />
			<Container maxW="container.xl">
				<Flex>
					<CategoryBar />
					{children}
				</Flex>
			</Container>
		</>
	);
};

export default Layout;
